// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52OXGda3lFydMxmmCx1_ZI42UeWWGHYc',
    appId: '1:1077546567574:web:78f36ca152dd1b86503fb7',
    messagingSenderId: '1077546567574',
    projectId: 'dynmiclist',
    authDomain: 'dynmiclist.firebaseapp.com',
    storageBucket: 'dynmiclist.firebasestorage.app',
    measurementId: 'G-JKHRLSJSCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGiu2XSCq-VGeKp-9aJ1JCiQNrDIMZcDg',
    appId: '1:1077546567574:android:c2a7be92516d9ec5503fb7',
    messagingSenderId: '1077546567574',
    projectId: 'dynmiclist',
    storageBucket: 'dynmiclist.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB52OXGda3lFydMxmmCx1_ZI42UeWWGHYc',
    appId: '1:1077546567574:web:e578822798ae6896503fb7',
    messagingSenderId: '1077546567574',
    projectId: 'dynmiclist',
    authDomain: 'dynmiclist.firebaseapp.com',
    storageBucket: 'dynmiclist.firebasestorage.app',
    measurementId: 'G-GED2ZGX35D',
  );
}
